# Site settings
title: AK-Hribik | Matej Hribik JUDR & Mgr. Nina Hribikova
description: "A responsive Jekyll theme for dental clinics."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.png

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: DentistSmile
    hero_description: A responsive Jekyll theme for dental clinics.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 932 50 540
    emergency: 931 53 234
    email: contact@yoursite.com
    address: Kukučínova 20, <br> 974 01 Banská Bystrica

# Opening hours
monday_friday: 8:00 – 16:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Kukučínova 20, 974 01 Banská Bystrica, Slovakia
    address_details: img/logo.png
    #address_details: svg/min/logo.svg
    google_maps_api_token: AIzaSyDXjeaQCQo3j411-c7c4iNIUzVHMRuwe8I

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2017 AK Hribik - All rights reserved.

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
